### ISSUE TITLE
Exporting vid error

### ISSUE THREAD

**Issue by innovadorx** [HA6Bots/Twitch-Clips-Compilation-Generator-TCCG-#2]
have an issue when exporting the final vid.
CLIENT CONSOLE LOG: https://prnt.sc/vdn9mp
VIDEO RENDER CONSOLE LOG: https://prnt.sc/vdn9av
CLIENT + GENERATOR = https://prnt.sc/vdn9mp
Its just not showing on client, if i click download, an empty mp4 its downloaded. No final video on client/server/generator
Not sure whats happening

**Comment by jobbie2** [comment]
I'm having the same issue
were you able to fix this problem?
